### ISSUE TITLE
Metadata version mismatch for module - found version 4, expected 3

### ISSUE THREAD

**Issue by amorel** [abhazelton/animate-on-scroll-test#2]
I am getting the following error while running ng serve command.

ERROR in Error: Metadata version mismatch for module I:/DOSSIER_Projects/animate-on-scroll-test-master/node_modules/ng2-animate-on-scroll/dist/index.d.ts, found version 4, expected 3, resolving symbol AppModule in I:/DOSSIER_Projects/animate-on-scroll-test-master/src/app/app.module.ts, resolving symbol AppModule in I:/DOSSIER_Projects/animate-on-scroll-test-master/src/app/app.module.ts, resolving symbol AppModule in I:/DOSSIER_Projects/animate-on-scroll-test-master/src/app/app.module.ts
    at syntaxError (I:\DOSSIER_Projects\animate-on-scroll-test-master\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (I:\DOSSIER_Projects\animate-on-scroll-test-master\node_modules\@angular\compiler\bundles\compiler.umd.js:25118:23)
    at StaticReflector.simplify (I:\DOSSIER_Projects\animate-on-scroll-test-master\node_modules\@angular\compiler\bundles\compiler.umd.js:25130:13)
    at StaticReflector.annotations (I:\DOSSIER_Projects\animate-on-scroll-test-master\node_modules\@angular\compiler\bundles\compiler.umd.js:24558:41)
    at _getNgModuleMetadata (I:\DOSSIER_Projects\animate-on-scroll-test-master\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (I:\DOSSIER_Projects\animate-on-scroll-test-master\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (I:\DOSSIER_Projects\animate-on-scroll-test-master\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (I:\DOSSIER_Projects\animate-on-scroll-test-master\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (I:\DOSSIER_Projects\animate-on-scroll-test-master\node_modules\@ngtools\webpack\src\plugin.js:240:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (I:\DOSSIER_Projects\animate-on-scroll-test-master\node_modules\@ngtools\webpack\src\plugin.js:493:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by abhazelton** [comment]
As you may have noticed, there hasn't been any updates in a while on this. I'm too busy to keep up with it and haven't been working on any Angular projects for a while, so if someone wants to take this over, you are welcome to it.
